package io.aiven.kafka.connect.amqp.source;

public enum AmqpProperties {
	MESSAGE_ID, USER_ID, TO, SUBJECT, REPLY_TO, CORRELATION_ID, CONTENT_TYPE, CONTENT_ENCODING, ABSOLUTE_EXPIRY, CREATION_TIME, GROUP_ID, GROUP_SEQUENCE, REPLY_TO_GROUP_ID
}
